### ISSUE TITLE
v8 warning issued after require('metrohash')

### ISSUE THREAD

**Issue by JulianTonti** [robertklep/node-metrohash#1]
After require('metrohash'), node dumps about 10 pages worth of warnings which seem to be the same thing over and over. At the core of it is a V8 warning as follows (note that metrohash functions fine nonetheless, for the time being):

==== C stack trace ===============================

 1: v8::Template::Set(v8::Local<v8::Name>, v8::Local<v8::Data>, v8::PropertyAttribute)
 2: NodeMetroHash<MetroHash64, 8>::Init(char const*, v8::Local<v8::Object>)
 3: InitAll(v8::Local<v8::Object>)
 4: node::DLOpen(v8::FunctionCallbackInfo<v8::Value> const&)
 5: v8::internal::FunctionCallbackArguments::Call(void (*)(v8::FunctionCallbackInfo<v8::Value> const&))
 6: v8::internal::MaybeHandle<v8::internal::Object> v8::internal::(anonymous namespace)::HandleApiCallHelper<false>(v8::internal::Isolate*, v8::internal::(anonymous namespace)::BuiltinArguments<(v8::internal::BuiltinExtraArguments)1>)
 7: v8::internal::Builtin_HandleApiCall(int, v8::internal::Object**, v8::internal::Isolate*)
 8: 0xb96d0e092a7
 9: 0xb96d0fc16c4
(node) v8::ObjectTemplate::Set() with non-primitive values is deprecated
(node) and will stop working in the next major release.

**Comment by robertklep** [comment]
Thanks :) Which version of Node is this?

**Comment by JulianTonti** [comment]
My bad, I should have stated that: 6.9.1
Running on OS X 10.12

**Comment by robertklep** [comment]
I have to admit that I haven't looked at this module for a while, hence the warnings. I'll take a look!

**Comment by robertklep** [comment]
@JulianTonti just published 1.5.0, try that.

I couldn't even get it to build on v6 and v7 due to outdated dependencies, but after updating those it works again.

**Comment by JulianTonti** [comment]
Rebuilt for 6.9.1 and it's It's fixed.
Updated to node 7.0.0, rebuilt again, still good.

Tight work mate!

**Comment by robertklep** [comment]
Thanks for testing! Closing issue 👍🏼
