### ISSUE TITLE
Can not install metrohash on Node with version 12.  

### ISSUE THREAD

**Issue by stefanmilic** [robertklep/node-metrohash#22]
<img width="1578" alt="Screenshot 2021-07-22 at 16 04 01" src="https://user-images.githubusercontent.com/33635169/126658006-70f21d10-4f32-4378-91d8-c4b0fff581e9.png">

I have tried npm rebuild and didt't work

**Comment by robertklep** [comment]
`npm rebuild` should work (or `npm run build`), but it will rebuild the module in the local (source) directory. You have to make sure it gets copied to its final location.

**Comment by stefanmilic** [comment]
I am using Aws lambda (node 12 version). Do you have any idea how can I rebuild the module?

**Comment by robertklep** [comment]
Install Node.js 12 locally (possibly using something like [`nvm`](https://github.com/nvm-sh/nvm)), build it, and copy over to AWS.

**Comment by stefanmilic** [comment]
Only is working if i reduce Aws Lambda node version to 10

**Comment by robertklep** [comment]
As long as you're getting `NODE_MODULE_VERSION` mismatch errors, you're not compiling for the correct Node.js version.
