### ISSUE TITLE
non-deterministic hash results

### ISSUE THREAD

**Issue by kurttheviking** [robertklep/node-metrohash#3]
I was evaluating this library and one thing caught my eye, not sure if it's intentional or not. In short, given the same input, it appears to be relatively easy to generate inconsistent hashes. For example:

```js
const MetroHash128 = require('metrohash').MetroHash128;

const now = Date.now();
const seen = new Set();

for (let i = 0; i < 1000000; i += 1) {
  const hash = new MetroHash128(now);

  hash.update('Hello/1.0 (World;)');

  seen.add(hash.digest());
}

console.log(seen.keys());
```

Produced the following output:

```js
SetIterator {
  '7367f8e233ea5037d82d94faec311316',
  'f71ba7b069656149839479c5d1823129'
}
```

If this is expected, I think it might be useful to note in the docs that the hash result is not necessarily the same each run. Thanks!

**Comment by kurttheviking** [comment]
(Note, it doesn't appear to matter what the `seed` value is originally set to.)

**Comment by robertklep** [comment]
Ouch, that's _not_ expected!

I usually develop my code on macOS, and for that OS, there's only one unique key generated per run (as it should). However, I just installed the same version on a Linux server, and I'm getting the same inconsistent results that you are getting.

I'll take a look at it ASAP.

**EDIT**: the issue occurs when hashing strings, hashing buffers works okay.

**Comment by robertklep** [comment]
I just pushed v2.2.0 to the NPM repo that should fix this issue.

The interesting thing is that this issue also wasn't caught by [Travis](https://travis-ci.org/robertklep/node-metrohash), which I'm pretty sure isn't running macOS.

**Comment by kurttheviking** [comment]
@robertklep thanks for the quick turnaround!
